export interface Product {
  id: string;
  title: string;
  price: string;
  imageUrl: string;
  amazonLink: string;
}

export interface Niche {
  slug: string;
  title: string;
  description: string;
  products: Product[];
}

// Tier B - Imágenes representativas por nicho (una por profesión)
const MEDICO_IMG = "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=500&q=80";
const DENTISTA_IMG = "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=500&q=80";
const VETERINARIO_IMG = "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80";
const PSICOLOGO_IMG = "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=500&q=80";
const FARMACEUTICO_IMG = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&q=80";
const FISIOTERAPEUTA_IMG = "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=500&q=80";
const ABOGADO_IMG = "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=500&q=80";
const CONTABLE_IMG = "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=500&q=80";
const PERIODISTA_IMG = "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=500&q=80";
const DISENADOR_IMG = "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&q=80";
const MECANICO_IMG = "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=500&q=80";
const ELECTRICISTA_IMG = "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500&q=80";
const CARPINTERO_IMG = "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&q=80";
const PELUQUERA_IMG = "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=500&q=80";
const FOTOGRAFO_IMG = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&q=80";
const POLICIA_IMG = "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=500&q=80";
const BOMBERO_IMG = "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500&q=80";
const CICLISTA_IMG = "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=500&q=80";
const RUNNER_IMG = "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=500&q=80";
const VIAJERO_IMG = "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=500&q=80";
const VINO_IMG = "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500&q=80";
const CAFE_IMG = "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&q=80";
const ESCRITOR_IMG = "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=500&q=80";
const BIOLOGO_IMG = "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=500&q=80";
const GEOLOGO_IMG = "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=500&q=80";
const MUSICO_IMG = "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=500&q=80";
const COCINERO_IMG = "https://images.unsplash.com/photo-1556910103-1c02745a30bf?w=500&q=80";
const PINTOR_IMG = "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=500&q=80";
const JARDINERO_IMG = "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500&q=80";
const CIENTIFICO_IMG = "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=500&q=80";
const INGENIERO_IMG = "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80";
const PILOTO_IMG = "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=500&q=80";
const AZAFATA_IMG = "https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=500&q=80";
const ENTRENADOR_IMG = "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&q=80";
const YOGA_IMG = "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&q=80";
const SURFERO_IMG = "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=500&q=80";
const BUZO_IMG = "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=500&q=80";
const TE_IMG = "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500&q=80";
const COLECCIONISTA_IMG = "https://images.unsplash.com/photo-1611706024654-5c92d34a40d2?w=500&q=80";
const ASTRONOMO_IMG = "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=500&q=80";
const HISTORIADOR_IMG = "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=500&q=80";
const ARQUEOLOGO_IMG = "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=500&q=80";
const ACTOR_IMG = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80";
const BAILARIN_IMG = "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=500&q=80";
const ARTISTA_IMG = "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=500&q=80";

export const NICHE_DATA: Niche[] = [
  // TIER A - 5 nichos con imágenes variadas
  {
    slug: "arquitectos",
    title: "Los Mejores Regalos para Arquitectos",
    description: "Descubre las mejores ideas de regalos para arquitectos. Herramientas profesionales, maquetas, libros de diseño y accesorios.",
    products: [
      { id: "1", title: "Escuadra de Arquitecto Premium 45/90", price: "24,99 €", imageUrl: "https://images.unsplash.com/photo-1581092335397-9583eb92d232?w=500&q=80", amazonLink: "#" },
      { id: "2", title: "Libro: Los 101 Detalles Constructivos", price: "35,00 €", imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&q=80", amazonLink: "#" },
      { id: "3", title: "Escala de Arquitecto Triangular", price: "12,50 €", imageUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=500&q=80", amazonLink: "#" },
      { id: "4", title: "Portaplanos Profesional A2", price: "18,90 €", imageUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=500&q=80", amazonLink: "#" },
      { id: "5", title: "Lámpara de Escritorio LED Flexible", price: "29,99 €", imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500&q=80", amazonLink: "#" },
      { id: "6", title: "Compás de Precisión Profesional", price: "19,50 €", imageUrl: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=500&q=80", amazonLink: "#" },
      { id: "7", title: "Set de Rotuladores para Bocetos", price: "34,99 €", imageUrl: "https://images.unsplash.com/photo-1515712952504-4b537d896588?w=500&q=80", amazonLink: "#" },
      { id: "8", title: "Regla T de Aluminio 60cm", price: "28,00 €", imageUrl: "https://images.unsplash.com/photo-1615822588102-140652875b1c?w=500&q=80", amazonLink: "#" },
      { id: "9", title: "Cuaderno de Bocetos Moleskine", price: "22,00 €", imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=500&q=80", amazonLink: "#" },
      { id: "10", title: "Maqueta de Edificio Recortable", price: "22,00 €", imageUrl: "https://images.unsplash.com/photo-1469957761306-556935073eba?w=500&q=80", amazonLink: "#" },
      { id: "11", title: "Tijeras de Precisión para Maquetas", price: "18,99 €", imageUrl: "https://images.unsplash.com/photo-1583947581924-860bda073c29?w=500&q=80", amazonLink: "#" },
      { id: "12", title: "Libro: Historia de la Arquitectura", price: "38,50 €", imageUrl: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&q=80", amazonLink: "#" },
    ],
  },
  {
    slug: "gamers",
    title: "Los Mejores Regalos para Gamers",
    description: "Ideas de regalos perfectas para gamers. Periféricos, merchandising, sillas gaming y accesorios.",
    products: [
      { id: "1", title: "Teclado Mecánico RGB Gaming", price: "89,99 €", imageUrl: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=500&q=80", amazonLink: "#" },
      { id: "2", title: "Auriculares Gaming Surround", price: "69,99 €", imageUrl: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=500&q=80", amazonLink: "#" },
      { id: "3", title: "Ratón Inalámbrico Ultra Ligero", price: "54,99 €", imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&q=80", amazonLink: "#" },
      { id: "4", title: "Alfombrilla XL Gaming", price: "19,99 €", imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500&q=80", amazonLink: "#" },
      { id: "5", title: "Soporte para Auriculares RGB", price: "24,90 €", imageUrl: "https://images.unsplash.com/photo-1614680376739-414d95ff43df?w=500&q=80", amazonLink: "#" },
      { id: "6", title: "Webcam 1080p Streaming", price: "79,00 €", imageUrl: "https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=500&q=80", amazonLink: "#" },
      { id: "7", title: "Silla Gamer Ergonómica", price: "249,99 €", imageUrl: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=500&q=80", amazonLink: "#" },
      { id: "8", title: "Monitores Gaming 144Hz", price: "329,00 €", imageUrl: "https://images.unsplash.com/photo-1547082299-de196ea013d6?w=500&q=80", amazonLink: "#" },
      { id: "9", title: "Controlador Pro Consola", price: "64,99 €", imageUrl: "https://images.unsplash.com/photo-1629429408209-1f912961dbd8?w=500&q=80", amazonLink: "#" },
      { id: "10", title: "Luces LED Ambientales", price: "29,99 €", imageUrl: "https://images.unsplash.com/photo-1563294326-78b174af9720?w=500&q=80", amazonLink: "#" },
      { id: "11", title: "Micrófono USB Streaming", price: "49,99 €", imageUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=500&q=80", amazonLink: "#" },
      { id: "12", title: "Hub USB Periféricos", price: "34,90 €", imageUrl: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=500&q=80", amazonLink: "#" },
    ],
  },
  {
    slug: "enfermeros",
    title: "Los Mejores Regalos para Enfermeros",
    description: "Regalos pensados para enfermeros y enfermeras. Productos para bienestar y comodidad en el trabajo.",
    products: [
      { id: "1", title: "Zapatillas Cómodas Trabajo", price: "45,99 €", imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80", amazonLink: "#" },
      { id: "2", title: "Reloj de Enfermería", price: "32,00 €", imageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500&q=80", amazonLink: "#" },
      { id: "3", title: "Botella Agua Térmica 1L", price: "22,50 €", imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&q=80", amazonLink: "#" },
      { id: "4", title: "Almohada Cervical Viaje", price: "28,99 €", imageUrl: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=500&q=80", amazonLink: "#" },
      { id: "5", title: "Libro: Anatomía Humana", price: "18,90 €", imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&q=80", amazonLink: "#" },
      { id: "6", title: "Linterna Médica Diagnóstico", price: "24,50 €", imageUrl: "https://images.unsplash.com/photo-1583324113626-70df0f4deaab?w=500&q=80", amazonLink: "#" },
      { id: "7", title: "Plantillas Gel Confort", price: "35,99 €", imageUrl: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500&q=80", amazonLink: "#" },
      { id: "8", title: "Mochila Sanitaria", price: "52,00 €", imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80", amazonLink: "#" },
      { id: "9", title: "Crema de Manos Reparadora", price: "16,90 €", imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&q=80", amazonLink: "#" },
      { id: "10", title: "Taza Café Enfermera", price: "14,99 €", imageUrl: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500&q=80", amazonLink: "#" },
      { id: "11", title: "Masajeador Cuello Portátil", price: "49,99 €", imageUrl: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=500&q=80", amazonLink: "#" },
      { id: "12", title: "Zuecos Sanitarios Blancos", price: "19,50 €", imageUrl: "https://images.unsplash.com/photo-1516478177764-9fe5bd7e9717?w=500&q=80", amazonLink: "#" },
    ],
  },
  {
    slug: "programadores",
    title: "Los Mejores Regalos para Programadores",
    description: "Ideas de regalos para desarrolladores. Teclados, libros técnicos, gadgets y accesorios.",
    products: [
      { id: "1", title: "Teclado Ergonómico Split", price: "129,99 €", imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b91a603?w=500&q=80", amazonLink: "#" },
      { id: "2", title: "Monitor 4K USB-C", price: "299,00 €", imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&q=80", amazonLink: "#" },
      { id: "3", title: "Libro: Clean Code", price: "42,95 €", imageUrl: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=500&q=80", amazonLink: "#" },
      { id: "4", title: "Soporte Laptop Aluminio", price: "34,99 €", imageUrl: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=500&q=80", amazonLink: "#" },
      { id: "5", title: 'Taza "Hello World"', price: "14,99 €", imageUrl: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=500&q=80", amazonLink: "#" },
      { id: "6", title: "Dock Station USB-C", price: "49,99 €", imageUrl: "https://images.unsplash.com/photo-1628126781211-1a3eb64f7836?w=500&q=80", amazonLink: "#" },
      { id: "7", title: "Auriculares Noise Cancelling", price: "89,00 €", imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&q=80", amazonLink: "#" },
      { id: "8", title: "Ratón Vertical Ergonómico", price: "59,99 €", imageUrl: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=500&q=80", amazonLink: "#" },
      { id: "9", title: "SSD Externo 1TB", price: "79,99 €", imageUrl: "https://images.unsplash.com/photo-1597872252165-230dd99d5079?w=500&q=80", amazonLink: "#" },
      { id: "10", title: "Gafas Luz Azul", price: "25,00 €", imageUrl: "https://images.unsplash.com/photo-1577803645773-f96470509666?w=500&q=80", amazonLink: "#" },
      { id: "11", title: "Webcam HD Pro", price: "99,99 €", imageUrl: "https://images.unsplash.com/photo-1596564239327-1c667e45668d?w=500&q=80", amazonLink: "#" },
      { id: "12", title: "Tira LED Escritorio", price: "39,90 €", imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=500&q=80", amazonLink: "#" },
    ],
  },
  {
    slug: "profesores",
    title: "Los Mejores Regalos para Profesores",
    description: "Regalos ideales para maestros y profesores. Material educativo, accesorios de escritorio y detalles de agradecimiento.",
    products: [
      { id: "1", title: "Bolígrafo Estilográfica Premium", price: "29,99 €", imageUrl: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=500&q=80", amazonLink: "#" },
      { id: "2", title: "Agenda Docente Año Completo", price: "24,90 €", imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80", amazonLink: "#" },
      { id: "3", title: "Taza Profesor con Frase Motivadora", price: "12,99 €", imageUrl: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=500&q=80", amazonLink: "#" },
      { id: "4", title: "Set de Marcadores para Pizarra", price: "18,50 €", imageUrl: "https://images.unsplash.com/photo-1588072432836-e10032774350?w=500&q=80", amazonLink: "#" },
      { id: "5", title: "Organizador de Escritorio", price: "34,99 €", imageUrl: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=500&q=80", amazonLink: "#" },
      { id: "6", title: "Libro: Pedagogía Moderna", price: "28,00 €", imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&q=80", amazonLink: "#" },
      { id: "7", title: "Laminán Térmico Portátil", price: "42,00 €", imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=500&q=80", amazonLink: "#" },
      { id: "8", title: "Bolsa Térmica para Almuerzo", price: "22,99 €", imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80", amazonLink: "#" },
      { id: "9", title: "Timer de Clase Visual", price: "19,90 €", imageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500&q=80", amazonLink: "#" },
      { id: "10", title: "Paquete de Stickers Educativos", price: "9,99 €", imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80", amazonLink: "#" },
      { id: "11", title: "Cuaderno Profesional A4", price: "14,50 €", imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=500&q=80", amazonLink: "#" },
      { id: "12", title: "Silla Ergonómica para Docentes", price: "189,99 €", imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80", amazonLink: "#" },
    ],
  },
  // TIER B - 45 nichos con imagen representativa única
  { slug: "medicos", title: "Los Mejores Regalos para Médicos", description: "Regalos para médicos y doctoras.", products: [
    { id: "1", title: "Estetoscopio Litmann Classic III", price: "89,99 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "2", title: "Reloj de Bolsillo Médico", price: "45,00 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "3", title: "Libro: Diagnóstico Clínico", price: "52,90 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "4", title: "Bata Clínica Premium", price: "38,99 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "5", title: "Maletín Doctor Cuero", price: "129,00 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "6", title: "Linterna Diagnóstica LED", price: "24,50 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "7", title: "Soporte Tablet para Consulta", price: "34,99 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "8", title: "Zapatos Clínicos Antideslizantes", price: "65,00 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "9", title: "Cuaderno de Recetas Médicas", price: "18,90 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "10", title: "Termo Acero Inoxidable", price: "22,99 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "11", title: "Gafas de Descanso Anti-Reflejo", price: "42,50 €", imageUrl: MEDICO_IMG, amazonLink: "#" }, { id: "12", title: "Pack Vitaminas y Omega 3", price: "28,00 €", imageUrl: MEDICO_IMG, amazonLink: "#" },
  ]},
  { slug: "dentistas", title: "Los Mejores Regalos para Dentistas", description: "Regalos para dentistas y odontólogos.", products: [
    { id: "1", title: "Modelo Dental Educativo", price: "34,99 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "2", title: "Lupa Dental con Luz", price: "48,00 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "3", title: "Set Cepillos Interdentales", price: "14,90 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "4", title: "Hilo Dental Premium Pack", price: "12,50 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "5", title: "Enjuague Bucal Profesional", price: "18,99 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "6", title: "Kit Higiene Dental Viaje", price: "24,00 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "7", title: "Cepillo Eléctrico Recargable", price: "59,99 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "8", title: "Irrigador Dental Portátil", price: "42,00 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "9", title: "Libro: Anatomía Dental", price: "45,90 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "10", title: "Almohada Cervical Memory Foam", price: "32,99 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "11", title: "Gafas Protección UV", price: "28,50 €", imageUrl: DENTISTA_IMG, amazonLink: "#" }, { id: "12", title: "Taza Sonrisa Perfecta", price: "11,99 €", imageUrl: DENTISTA_IMG, amazonLink: "#" },
  ]},
  { slug: "veterinarios", title: "Los Mejores Regalos para Veterinarios", description: "Regalos para veterinarios y amantes de animales.", products: [
    { id: "1", title: "Estetoscopio Veterinario", price: "78,99 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "2", title: "Bata Clínica Veterinaria", price: "44,00 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "3", title: "Guantes Exploración Nitrilo", price: "14,90 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "4", title: "Termómetro Digital Veterinario", price: "22,50 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "5", title: "Libro: Medicina Veterinaria", price: "56,99 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "6", title: "Taza Amor por los Animales", price: "12,99 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "7", title: "Linterna Diagnóstica Veterinaria", price: "35,00 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "8", title: "Maletín Instrumental Veterinario", price: "89,99 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "9", title: "Mascarilla Desechable Pack", price: "18,50 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "10", title: "Figura Estetoscopio Veterinario", price: "24,90 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "11", title: "Báscula Digital Pequeños Animales", price: "42,00 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" }, { id: "12", title: "Agenda Veterinaria 2025", price: "19,99 €", imageUrl: VETERINARIO_IMG, amazonLink: "#" },
  ]},
  { slug: "psicologos", title: "Los Mejores Regalos para Psicólogos", description: "Regalos para psicólogos y terapeutas.", products: [
    { id: "1", title: "Reloj de Arena Terapia", price: "24,99 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "2", title: "Libro: Psicología Cognitiva", price: "38,00 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "3", title: "Cuaderno de Notas Terapéuticas", price: "18,90 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "4", title: "Silla Ergonómica Consulta", price: "249,99 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "5", title: "Lámpara de Ambiente LED", price: "34,99 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "6", title: "Set de Tarjetas Mindfulness", price: "22,50 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "7", title: "Taza Psicólogo con Mensaje", price: "12,99 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "8", title: "Difusor Aromaterapia", price: "42,00 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "9", title: "Organizador de Escritorio Minimalista", price: "28,90 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "10", title: "Agenda Profesional A5", price: "24,99 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "11", title: "Reloj Silencioso Consulta", price: "35,00 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" }, { id: "12", title: "Pack Aceites Esenciales", price: "29,90 €", imageUrl: PSICOLOGO_IMG, amazonLink: "#" },
  ]},
  { slug: "farmaceuticos", title: "Los Mejores Regalos para Farmacéuticos", description: "Regalos para farmacéuticos.", products: [
    { id: "1", title: "Bata de Farmacia Blanca", price: "45,99 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "2", title: "Calculadora Científica Profesional", price: "28,00 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "3", title: "Libro: Farmacología", price: "52,90 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "4", title: "Organizador Pastillero Semanal", price: "14,99 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "5", title: "Lupa de Farmacia", price: "22,50 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "6", title: "Báscula de Precisión Digital", price: "38,00 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "7", title: "Termo Acero Inoxidable 1L", price: "24,99 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "8", title: "Zapatos Cómodos para Turnos", price: "65,00 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "9", title: "Agenda Farmacéutica 2025", price: "19,90 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "10", title: "Taza Farmacia con Fórmula", price: "11,99 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "11", title: "Luz de Escritorio LED", price: "32,50 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" }, { id: "12", title: "Pack Suplementos Vitamina D", price: "18,00 €", imageUrl: FARMACEUTICO_IMG, amazonLink: "#" },
  ]},
  { slug: "fisioterapeutas", title: "Los Mejores Regalos para Fisioterapeutas", description: "Regalos para fisioterapeutas.", products: [
    { id: "1", title: "Pelota de Masaje Terapéutica", price: "18,99 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "2", title: "Rodillo Foam Profesional", price: "34,00 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "3", title: "Banda Elástica Set Resistencia", price: "22,90 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "4", title: "Libro: Anatomía Funcional", price: "45,99 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "5", title: "Crema Calentadora Muscular", price: "14,50 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "6", title: "Silla de Masaje Portátil", price: "89,00 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "7", title: "Tabla Anatómica del Cuerpo", price: "28,99 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "8", title: "Guantes Masaje Profesionales", price: "24,00 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "9", title: "Almohada Lumbar Ergonómica", price: "42,90 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "10", title: "Tens Eléctrico Portátil", price: "38,99 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "11", title: "Colchoneta Yoga Profesional", price: "32,00 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" }, { id: "12", title: "Aceite de Masaje Profesional", price: "19,50 €", imageUrl: FISIOTERAPEUTA_IMG, amazonLink: "#" },
  ]},
  { slug: "abogados", title: "Los Mejores Regalos para Abogados", description: "Regalos para abogados y juristas.", products: [
    { id: "1", title: "Estuche Cuero para Documentos", price: "48,99 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "2", title: "Bolígrafo Montblanc", price: "189,00 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "3", title: "Agenda Ejecutiva Cuero", price: "45,90 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "4", title: "Libro: Código Civil", price: "32,99 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "5", title: "Carpeta Portafolios A4", price: "28,50 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "6", title: "Reloj de Pulsera Elegante", price: "95,00 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "7", title: "Tarjetero Cuero", price: "24,99 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "8", title: "Taza Justicia con Balanza", price: "12,99 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "9", title: "Soporte Tablet Escritorio", price: "34,90 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "10", title: "Corbata de Seda", price: "42,00 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "11", title: "Organizador de Expedientes", price: "38,99 €", imageUrl: ABOGADO_IMG, amazonLink: "#" }, { id: "12", title: "Lámpara Escritorio LED", price: "54,00 €", imageUrl: ABOGADO_IMG, amazonLink: "#" },
  ]},
  { slug: "contables", title: "Los Mejores Regalos para Contables", description: "Regalos para contables y asesores fiscales.", products: [
    { id: "1", title: "Calculadora Financiera HP", price: "89,99 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "2", title: "Organizador de Facturas", price: "24,00 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "3", title: "Libro: Fiscalidad 2025", price: "42,90 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "4", title: "Agenda Ejecutiva Semanal", price: "28,99 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "5", title: "Silla Ergonómica Oficina", price: "199,00 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "6", title: "Carpeta Archivador A4", price: "18,50 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "7", title: "Monitor Dual 24 pulgadas", price: "249,99 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "8", title: "Teclado Numérico USB", price: "32,00 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "9", title: "Taza Contador con Fórmula", price: "11,99 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "10", title: "Sobres de Clasificación", price: "14,90 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "11", title: "Luz de Escritorio Antifatiga", price: "38,50 €", imageUrl: CONTABLE_IMG, amazonLink: "#" }, { id: "12", title: "Planner Semanal Cuadriculado", price: "19,99 €", imageUrl: CONTABLE_IMG, amazonLink: "#" },
  ]},
  { slug: "periodistas", title: "Los Mejores Regalos para Periodistas", description: "Regalos para periodistas y comunicadores.", products: [
    { id: "1", title: "Cuaderno Moleskine Reporter", price: "22,99 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "2", title: "Bolígrafo Pilot G2 Pack", price: "12,00 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "3", title: "Grabadora Digital Profesional", price: "89,90 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "4", title: "Libro: Redacción Periodística", price: "28,99 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "5", title: "Mochila Portátil Antirrobo", price: "65,00 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "6", title: "Cargador Portátil Universal", price: "34,50 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "7", title: "Taza Prensa con Título", price: "9,99 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "8", title: "Agenda Periodística 2025", price: "24,00 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "9", title: "Tablet iPad para Notas", price: "399,99 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "10", title: "Auriculares con Cancelación Ruido", price: "79,90 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "11", title: "Linterna LED Bolsillo", price: "18,50 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" }, { id: "12", title: "Libreta Field Notes Pack", price: "14,99 €", imageUrl: PERIODISTA_IMG, amazonLink: "#" },
  ]},
  { slug: "disenadores-graficos", title: "Los Mejores Regalos para Diseñadores Gráficos", description: "Regalos para diseñadores gráficos.", products: [
    { id: "1", title: "Tableta Gráfica Wacom", price: "129,99 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "2", title: "Monitor Color Calibrado", price: "349,00 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "3", title: "Libro: Diseño y Comunicación", price: "42,90 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "4", title: "Set Rotuladores Copic", price: "89,99 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "5", title: "Ratón Ergonómico Vertical", price: "54,00 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "6", title: "Pantone Color Guide", price: "78,50 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "7", title: "Taza Diseñador con Frase", price: "12,99 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "8", title: "Cuaderno Sketch A4", price: "22,00 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "9", title: "Soporte Laptop Ajustable", price: "38,90 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "10", title: "Lápices Grafito Profesionales", price: "28,99 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "11", title: "Gafas Luz Azul", price: "35,00 €", imageUrl: DISENADOR_IMG, amazonLink: "#" }, { id: "12", title: "USB Hub USB-C", price: "42,50 €", imageUrl: DISENADOR_IMG, amazonLink: "#" },
  ]},
  { slug: "mecanicos", title: "Los Mejores Regalos para Mecánicos", description: "Regalos para mecánicos y técnicos.", products: [
    { id: "1", title: "Juego Llaves Combinadas", price: "45,99 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "2", title: "Guantes de Trabajo", price: "18,00 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "3", title: "Linterna Recargable LED", price: "28,90 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "4", title: "Caja Herramientas 3 Niveles", price: "89,99 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "5", title: "Zapatos de Seguridad", price: "65,00 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "6", title: "Manómetro Neumático", price: "42,50 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "7", title: "Taza Mecánico con Fórmula", price: "11,99 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "8", title: "Alfombrilla Antifatiga", price: "54,00 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "9", title: "Juego Destornilladores Phillips", price: "24,90 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "10", title: "Cremallera Ropa Trabajo", price: "32,99 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "11", title: "Calendario Coches Clásicos", price: "14,00 €", imageUrl: MECANICO_IMG, amazonLink: "#" }, { id: "12", title: "Botella Térmica Acero", price: "22,50 €", imageUrl: MECANICO_IMG, amazonLink: "#" },
  ]},
  { slug: "electricistas", title: "Los Mejores Regalos para Electricistas", description: "Regalos para electricistas.", products: [
    { id: "1", title: "Multímetro Digital Profesional", price: "45,99 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "2", title: "Detector de Tensión", price: "22,00 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "3", title: "Juego Alicates Aislados", price: "38,90 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "4", title: "Cinturón Portaherramientas", price: "42,99 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "5", title: "Guantes Aislantes Alta Tensión", price: "55,00 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "6", title: "Linterna Frontal Recargable", price: "28,50 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "7", title: "Destornilladores Electricista", price: "24,99 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "8", title: "Cinta Aislante Pack", price: "12,00 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "9", title: "Pelacables Automático", price: "18,90 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "10", title: "Libro: Instalaciones Eléctricas", price: "45,99 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "11", title: "Taza Electricista con Voltaje", price: "9,99 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" }, { id: "12", title: "Organizador Cables", price: "19,50 €", imageUrl: ELECTRICISTA_IMG, amazonLink: "#" },
  ]},
  { slug: "carpinteros", title: "Los Mejores Regalos para Carpinteros", description: "Regalos para carpinteros y ebanistas.", products: [
    { id: "1", title: "Sierra de Calar Eléctrica", price: "89,99 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "2", title: "Juego Formones Profesional", price: "45,00 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "3", title: "Escuadra Carpintero 90", price: "18,90 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "4", title: "Martillo Carpintero", price: "24,99 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "5", title: "Cepillo Manual Madera", price: "38,00 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "6", title: "Guantes de Trabajo", price: "14,50 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "7", title: "Metro Plegable 5m", price: "12,99 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "8", title: "Lija Set Granos Variados", price: "22,00 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "9", title: "Taladro Atornillador Inalámbrico", price: "79,90 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "10", title: "Taza Carpintero con Medidas", price: "11,99 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "11", title: "Bata de Trabajo", price: "32,50 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" }, { id: "12", title: "Libro: Ebanistería Clásica", price: "35,00 €", imageUrl: CARPINTERO_IMG, amazonLink: "#" },
  ]},
  { slug: "peluqueras", title: "Los Mejores Regalos para Peluqueras", description: "Regalos para peluqueras y estilistas.", products: [
    { id: "1", title: "Tijeras de Corte Profesionales", price: "65,99 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "2", title: "Secador Iónico Profesional", price: "89,00 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "3", title: "Plancha de Pelo Cerámica", price: "54,90 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "4", title: "Peine Profesional", price: "12,99 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "5", title: "Cepillo Redondo Cerámico", price: "22,00 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "6", title: "Delantal Peluquería", price: "18,50 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "7", title: "Secador de Manos Profesional", price: "42,99 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "8", title: "Set Horquillas y Pinzas", price: "14,00 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "9", title: "Aceite Capilar Argan", price: "24,90 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "10", title: "Espejo Amplificador", price: "28,99 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "11", title: "Taza Peluquera con Mensaje", price: "9,99 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" }, { id: "12", title: "Organizador Utensilios", price: "32,50 €", imageUrl: PELUQUERA_IMG, amazonLink: "#" },
  ]},
  { slug: "fotografos", title: "Los Mejores Regalos para Fotógrafos", description: "Regalos para fotógrafos.", products: [
    { id: "1", title: "Trípode Compacto Profesional", price: "89,99 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "2", title: "Disparador Remoto Inalámbrico", price: "24,00 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "3", title: "Filtro ND Variable", price: "45,90 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "4", title: "Bolsa Cámara Impermeable", price: "65,99 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "5", title: "Tarjeta SD 128GB", price: "32,00 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "6", title: "Saco de Dormir Cámara", price: "18,50 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "7", title: "Libro: Composición Fotográfica", price: "28,99 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "8", title: "Linterna LED Portátil", price: "22,00 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "9", title: "Taza Fotógrafo con Objetivo", price: "12,99 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "10", title: "Mochila Fotografía", price: "79,90 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "11", title: "Disco Difusor Portátil", price: "34,50 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" }, { id: "12", title: "Limpieza Sensores Kit", price: "24,99 €", imageUrl: FOTOGRAFO_IMG, amazonLink: "#" },
  ]},
  { slug: "policias", title: "Los Mejores Regalos para Policías", description: "Regalos para policías y agentes.", products: [
    { id: "1", title: "Linterna Táctica LED", price: "45,99 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "2", title: "Reloj Resistente Militar", price: "89,00 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "3", title: "Botas Tácticas", price: "95,90 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "4", title: "Mochila Táctica", price: "54,99 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "5", title: "Navaja Multiusos", price: "38,00 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "6", title: "Cargador Portátil 20000mAh", price: "28,50 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "7", title: "Guantes Tácticos", price: "24,99 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "8", title: "Cuaderno Campo", price: "14,00 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "9", title: "Taza Policía con Mensaje", price: "11,99 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "10", title: "Botella Térmica Acero", price: "22,90 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "11", title: "Cinturón Táctico", price: "42,50 €", imageUrl: POLICIA_IMG, amazonLink: "#" }, { id: "12", title: "First Aid Kit Compacto", price: "19,99 €", imageUrl: POLICIA_IMG, amazonLink: "#" },
  ]},
  { slug: "bomberos", title: "Los Mejores Regalos para Bomberos", description: "Regalos para bomberos.", products: [
    { id: "1", title: "Linterna Recargable Potente", price: "45,99 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "2", title: "Reloj Resistente Agua", price: "65,00 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "3", title: "Botas de Seguridad", price: "89,90 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "4", title: "Mochila Táctica", price: "54,99 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "5", title: "Multiherramienta", price: "42,00 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "6", title: "Taza Bombero con Mensaje", price: "12,99 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "7", title: "Guantes Resistente Calor", price: "35,50 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "8", title: "Figura Bombero Coleccionable", price: "24,00 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "9", title: "Botella Agua 1L", price: "18,90 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "10", title: "Pulsera Identificación", price: "14,99 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "11", title: "Libro: Historia Bomberos", price: "28,50 €", imageUrl: BOMBERO_IMG, amazonLink: "#" }, { id: "12", title: "Crema Manos Reparadora", price: "16,00 €", imageUrl: BOMBERO_IMG, amazonLink: "#" },
  ]},
  { slug: "ciclistas", title: "Los Mejores Regalos para Ciclistas", description: "Regalos para ciclistas.", products: [
    { id: "1", title: "Gafas Ciclismo Sol", price: "45,99 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "2", title: "Cascos Aerodinámico", price: "89,00 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "3", title: "Culotte Padded Profesional", price: "65,90 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "4", title: "Bidón Ciclismo", price: "12,99 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "5", title: "Luces LED Delanteras", price: "28,00 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "6", title: "Guantes Ciclismo", price: "24,50 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "7", title: "Cámara Bomba Portátil", price: "35,99 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "8", title: "Ordenador Ciclismo GPS", price: "149,00 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "9", title: "Jersey Manga Corta", price: "42,90 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "10", title: "Gel Energético Pack", price: "18,99 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "11", title: "Toallitas Mochila", price: "22,00 €", imageUrl: CICLISTA_IMG, amazonLink: "#" }, { id: "12", title: "Taza Ciclista con Mensaje", price: "11,99 €", imageUrl: CICLISTA_IMG, amazonLink: "#" },
  ]},
  { slug: "runners", title: "Los Mejores Regalos para Runners", description: "Regalos para corredores.", products: [
    { id: "1", title: "Zapatillas Running", price: "129,99 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "2", title: "Reloj GPS Correr", price: "199,00 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "3", title: "Riñonera Running", price: "24,90 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "4", title: "Auriculares Deportivos", price: "45,99 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "5", title: "Camiseta Técnica", price: "35,00 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "6", title: "Gel Energético", price: "14,50 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "7", title: "Pulsera Reflectante", price: "9,99 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "8", title: "Rodillo Foam Masaje", price: "32,00 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "9", title: "Banda Cabeza Sudor", price: "12,90 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "10", title: "Botella Correr Portátil", price: "18,99 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "11", title: "Libro: Entrenamiento Running", price: "22,50 €", imageUrl: RUNNER_IMG, amazonLink: "#" }, { id: "12", title: "Taza Runner", price: "11,99 €", imageUrl: RUNNER_IMG, amazonLink: "#" },
  ]},
  { slug: "viajeros", title: "Los Mejores Regalos para Viajeros", description: "Regalos para viajeros.", products: [
    { id: "1", title: "Mochila Viaje 40L", price: "89,99 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "2", title: "Adaptador Universal", price: "24,00 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "3", title: "Cartera RFID", price: "22,90 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "4", title: "Almohada Cervical Viaje", price: "28,99 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "5", title: "Power Bank 20000mAh", price: "35,00 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "6", title: "Libro Guía Viajes", price: "18,50 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "7", title: "Cantimplora Plegable", price: "14,99 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "8", title: "Cámara Compacta", price: "199,00 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "9", title: "Organizador Maleta", price: "24,90 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "10", title: "Linterna Compacta", price: "18,99 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "11", title: "Cuaderno Viajero", price: "22,00 €", imageUrl: VIAJERO_IMG, amazonLink: "#" }, { id: "12", title: "Taza Viajero con Mapa", price: "12,99 €", imageUrl: VIAJERO_IMG, amazonLink: "#" },
  ]},
  { slug: "amantes-vino", title: "Los Mejores Regalos para Amantes del Vino", description: "Regalos para amantes del vino.", products: [
    { id: "1", title: "Sacacorchos Sommelier", price: "45,99 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "2", title: "Copas Vino Tinto Set", price: "38,00 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "3", title: "Libro: Catas de Vino", price: "28,90 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "4", title: "Decantador Cristal", price: "42,99 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "5", title: "Abrerchalas Premium", price: "24,00 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "6", title: "Temperador Vino", price: "32,50 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "7", title: "Tabla Quesos Madera", price: "35,99 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "8", title: "Tapa Corcho Decorativa", price: "14,00 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "9", title: "Vino Reserva Especial", price: "45,90 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "10", title: "Porta Copas", price: "18,99 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "11", title: "Cuaderno Cata", price: "22,00 €", imageUrl: VINO_IMG, amazonLink: "#" }, { id: "12", title: "Taza Sommelier", price: "11,99 €", imageUrl: VINO_IMG, amazonLink: "#" },
  ]},
  { slug: "amantes-cafe", title: "Los Mejores Regalos para Amantes del Café", description: "Regalos para amantes del café.", products: [
    { id: "1", title: "Cafetera Italiana", price: "35,99 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "2", title: "Molino Café Manual", price: "45,00 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "3", title: "Taza Cerámica Barista", price: "18,90 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "4", title: "French Press Vidrio", price: "28,99 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "5", title: "Café en Grano Premium", price: "22,00 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "6", title: "Termómetro Leche", price: "24,50 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "7", title: "Vaporizador Leche", price: "42,99 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "8", title: "Set Cucharas Medidoras", price: "14,00 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "9", title: "Libro: Arte del Café", price: "28,90 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "10", title: "Portafiltros Manual", price: "38,99 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "11", title: "Bote Conservación Café", price: "18,00 €", imageUrl: CAFE_IMG, amazonLink: "#" }, { id: "12", title: "Delantal Barista", price: "22,50 €", imageUrl: CAFE_IMG, amazonLink: "#" },
  ]},
  { slug: "escritores", title: "Los Mejores Regalos para Escritores", description: "Regalos para escritores.", products: [
    { id: "1", title: "Cuaderno Moleskine", price: "22,99 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "2", title: "Bolígrafo Estilográfica", price: "45,00 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "3", title: "Libro: Cómo Escribir", price: "18,90 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "4", title: "Soporte Laptop Ergonómico", price: "38,99 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "5", title: "Taza Escritor con Frase", price: "12,99 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "6", title: "Lámpara Escritorio", price: "42,50 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "7", title: "Auriculares Cancelación Ruido", price: "89,00 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "8", title: "Agenda Creativa", price: "24,99 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "9", title: "Diccionario RAE", price: "32,00 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "10", title: "Pack Post-its Color", price: "9,90 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "11", title: "Pluma Tinta Negra", price: "28,50 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" }, { id: "12", title: "Funda Cuero Portátil", price: "35,99 €", imageUrl: ESCRITOR_IMG, amazonLink: "#" },
  ]},
  { slug: "biologos", title: "Los Mejores Regalos para Biólogos", description: "Regalos para biólogos.", products: [
    { id: "1", title: "Microscopio Portátil", price: "89,99 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "2", title: "Libro: Biología Molecular", price: "52,00 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "3", title: "Cuaderno Campo", price: "18,90 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "4", title: "Lupa de Campo", price: "24,99 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "5", title: "Bata Laboratorio", price: "35,00 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "6", title: "Guantes Nitrilo Pack", price: "14,50 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "7", title: "Taza ADN", price: "11,99 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "8", title: "Botella Térmica", price: "22,00 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "9", title: "Lámpara UV Portátil", price: "38,90 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "10", title: "Reloj Cronómetro", price: "28,99 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "11", title: "Portamuestras", price: "18,00 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" }, { id: "12", title: "Gafas Protección", price: "24,50 €", imageUrl: BIOLOGO_IMG, amazonLink: "#" },
  ]},
  { slug: "geologos", title: "Los Mejores Regalos para Geólogos", description: "Regalos para geólogos.", products: [
    { id: "1", title: "Martillo Geólogo", price: "32,99 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "2", title: "Lupa de Campo 10x", price: "24,00 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "3", title: "Libro: Geología", price: "45,90 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "4", title: "Brújula Geológica", price: "38,99 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "5", title: "Botella Campo", price: "18,00 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "6", title: "Cuaderno Campo Impermeable", price: "22,50 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "7", title: "Bolsas Muestras", price: "14,99 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "8", title: "Bota Montaña", price: "89,00 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "9", title: "Taza Geólogo", price: "11,99 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "10", title: "GPS Portátil", price: "129,90 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "11", title: "Linterna Cabeza", price: "28,99 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" }, { id: "12", title: "Set Identificación Minerales", price: "35,00 €", imageUrl: GEOLOGO_IMG, amazonLink: "#" },
  ]},
  { slug: "musicos", title: "Los Mejores Regalos para Músicos", description: "Regalos para músicos.", products: [
    { id: "1", title: "Metrónomo Digital", price: "24,99 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "2", title: "Afinador Clip", price: "18,00 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "3", title: "Atril Plegable", price: "28,90 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "4", title: "Libro: Teoría Musical", price: "32,99 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "5", title: "Fundas Cuerdas Guitarra", price: "12,00 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "6", title: "Soporte Instrumento", price: "22,50 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "7", title: "Tapa Metrónomo", price: "14,99 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "8", title: "Auriculares Estudio", price: "79,00 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "9", title: "Partituras Vacías", price: "9,90 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "10", title: "Taza Músico", price: "11,99 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "11", title: "Cable Instrumento", price: "18,99 €", imageUrl: MUSICO_IMG, amazonLink: "#" }, { id: "12", title: "Grabadora Portátil", price: "65,00 €", imageUrl: MUSICO_IMG, amazonLink: "#" },
  ]},
  { slug: "cocineros", title: "Los Mejores Regalos para Cocineros", description: "Regalos para cocineros.", products: [
    { id: "1", title: "Set Cuchillos Chef", price: "89,99 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "2", title: "Tabla Corte Madera", price: "45,00 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "3", title: "Termómetro Cocina", price: "28,50 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "4", title: "Libro: Alta Cocina", price: "32,90 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "5", title: "Delantal Chef", price: "24,99 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "6", title: "Olla Cocción Lenta", price: "79,99 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "7", title: "Sartén Hierro", price: "64,90 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "8", title: "Báscula Digital", price: "18,50 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "9", title: "Robot Amasadora", price: "149,99 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "10", title: "Mortero Granito", price: "34,00 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "11", title: "Cuchillo Pan", price: "42,99 €", imageUrl: COCINERO_IMG, amazonLink: "#" }, { id: "12", title: "Manoplas Horno", price: "22,00 €", imageUrl: COCINERO_IMG, amazonLink: "#" },
  ]},
  { slug: "pintores", title: "Los Mejores Regalos para Pintores", description: "Regalos para pintores.", products: [
    { id: "1", title: "Set Pinceles Profesional", price: "45,99 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "2", title: "Paleta Madera", price: "18,00 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "3", title: "Lienzos Pack 5", price: "28,90 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "4", title: "Tubos Óleo Set", price: "42,99 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "5", title: "Caballete Plegable", price: "65,00 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "6", title: "Libro: Técnicas Pintura", price: "24,50 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "7", title: "Bata Pintor", price: "22,99 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "8", title: "Cuaderno Sketch", price: "14,00 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "9", title: "Taza Pintor", price: "11,99 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "10", title: "Spray Fijador", price: "12,90 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "11", title: "Acuarelas Set", price: "38,99 €", imageUrl: PINTOR_IMG, amazonLink: "#" }, { id: "12", title: "Easel Pared", price: "54,00 €", imageUrl: PINTOR_IMG, amazonLink: "#" },
  ]},
  { slug: "jardineros", title: "Los Mejores Regalos para Jardineros", description: "Regalos para jardineros.", products: [
    { id: "1", title: "Tijeras Podar", price: "28,99 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "2", title: "Guantes Jardinería", price: "18,00 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "3", title: "Regadera Metal", price: "24,90 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "4", title: "Libro: Plantas", price: "32,99 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "5", title: "Palas Set", price: "35,00 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "6", title: "Macetas Barro Set", price: "28,50 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "7", title: "Taza Jardinería", price: "11,99 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "8", title: "Kneeler Jardín", price: "42,00 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "9", title: "Semillas Huerto", price: "14,90 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "10", title: "Manguera Extensible", price: "38,99 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "11", title: "Carretilla Plegable", price: "65,00 €", imageUrl: JARDINERO_IMG, amazonLink: "#" }, { id: "12", title: "Delantal Jardinería", price: "22,50 €", imageUrl: JARDINERO_IMG, amazonLink: "#" },
  ]},
  { slug: "cientificos", title: "Los Mejores Regalos para Científicos", description: "Regalos para científicos.", products: [
    { id: "1", title: "Cuaderno Laboratorio", price: "18,99 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "2", title: "Bata Laboratorio", price: "35,00 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "3", title: "Libro: Método Científico", price: "28,90 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "4", title: "Calculadora Científica", price: "42,99 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "5", title: "Taza Fórmula Química", price: "12,99 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "6", title: "Reloj Cronómetro", price: "24,50 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "7", title: "Gafas Protección", price: "18,99 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "8", title: "Lámpara UV", price: "38,00 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "9", title: "Microscopio USB", price: "89,90 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "10", title: "Set Tubos Ensayo", price: "22,99 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "11", title: "Pizarra Magnética", price: "45,00 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" }, { id: "12", title: "Figura ADN", price: "28,50 €", imageUrl: CIENTIFICO_IMG, amazonLink: "#" },
  ]},
  { slug: "ingenieros", title: "Los Mejores Regalos para Ingenieros", description: "Regalos para ingenieros.", products: [
    { id: "1", title: "Calculadora Ingeniería", price: "89,99 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "2", title: "Regla Escala", price: "14,00 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "3", title: "Libro: Ingeniería", price: "45,90 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "4", title: "Escuadra Dibujo", price: "18,99 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "5", title: "Portátil Workstation", price: "1299,00 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "6", title: "Taza Ingeniero", price: "11,99 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "7", title: "Raspberry Pi Kit", price: "89,00 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "8", title: "Multímetro Digital", price: "42,50 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "9", title: "Cuaderno Cuadriculado", price: "12,90 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "10", title: "Boli Técnico", price: "22,99 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "11", title: "Laptop Stand", price: "38,00 €", imageUrl: INGENIERO_IMG, amazonLink: "#" }, { id: "12", title: "USB Hub", price: "28,50 €", imageUrl: INGENIERO_IMG, amazonLink: "#" },
  ]},
  { slug: "pilotos", title: "Los Mejores Regalos para Pilotos", description: "Regalos para pilotos.", products: [
    { id: "1", title: "Gafas Sol Aviador", price: "89,99 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "2", title: "Maletín Piloto Cuero", price: "129,00 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "3", title: "Reloj Cronógrafo", price: "199,90 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "4", title: "Libro: Historia Aviación", price: "32,99 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "5", title: "Mapa Aeronáutico", price: "24,00 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "6", title: "Taza Piloto", price: "12,99 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "7", title: "Linterna Táctica", price: "38,50 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "8", title: "Maqueta Avión", price: "45,00 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "9", title: "Cuaderno Bitácora", price: "18,90 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "10", title: "Adaptador Universal", price: "22,99 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "11", title: "Power Bank", price: "28,00 €", imageUrl: PILOTO_IMG, amazonLink: "#" }, { id: "12", title: "Figura Avión", price: "34,50 €", imageUrl: PILOTO_IMG, amazonLink: "#" },
  ]},
  { slug: "azafatas", title: "Los Mejores Regalos para Azafatas", description: "Regalos para azafatas.", products: [
    { id: "1", title: "Maleta Cabina", price: "89,99 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "2", title: "Reloj Elegante", price: "65,00 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "3", title: "Zapatos Cómodos", price: "75,90 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "4", title: "Bolso Organizador", price: "45,99 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "5", title: "Crema Manos", price: "14,00 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "6", title: "Almohada Cervical", price: "24,50 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "7", title: "Botella Térmica", price: "22,99 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "8", title: "Gafas Sol", price: "85,00 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "9", title: "Taza Azafata", price: "11,99 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "10", title: "Adaptador Universal", price: "18,90 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "11", title: "Cuaderno Viaje", price: "16,99 €", imageUrl: AZAFATA_IMG, amazonLink: "#" }, { id: "12", title: "Kit Maquillaje Viaje", price: "32,00 €", imageUrl: AZAFATA_IMG, amazonLink: "#" },
  ]},
  { slug: "entrenadores", title: "Los Mejores Regalos para Entrenadores", description: "Regalos para entrenadores personales.", products: [
    { id: "1", title: "Silbato Profesional", price: "12,99 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "2", title: "Cronómetro Deportivo", price: "28,00 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "3", title: "Banda Elástica Set", price: "22,90 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "4", title: "Rodillo Foam", price: "34,99 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "5", title: "Libro: Entrenamiento", price: "28,00 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "6", title: "Taza Entrenador", price: "11,99 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "7", title: "Reloj Deportivo", price: "89,50 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "8", title: "Camiseta Técnica", price: "24,99 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "9", title: "Tabla Ejercicios", price: "18,90 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "10", title: "Botella Agua", price: "16,99 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "11", title: "Gel Energético Pack", price: "14,00 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" }, { id: "12", title: "Cuaderno Planificación", price: "19,50 €", imageUrl: ENTRENADOR_IMG, amazonLink: "#" },
  ]},
  { slug: "yoga", title: "Los Mejores Regalos para Amantes del Yoga", description: "Regalos para practicantes de yoga.", products: [
    { id: "1", title: "Colchoneta Yoga Premium", price: "45,99 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "2", title: "Bloques Yoga EVA", price: "18,00 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "3", title: "Cinturón Yoga", price: "14,90 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "4", title: "Ropa Yoga Set", price: "42,99 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "5", title: "Libro: Asanas", price: "24,00 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "6", title: "Difusor Aromaterapia", price: "35,50 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "7", title: "Taza Yoga", price: "11,99 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "8", title: "Banda Elástica", price: "12,99 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "9", title: "Almohada Meditación", price: "28,90 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "10", title: "Velas Aromáticas", price: "18,99 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "11", title: "Manta Meditación", price: "32,00 €", imageUrl: YOGA_IMG, amazonLink: "#" }, { id: "12", title: "Toalla Yoga", price: "24,50 €", imageUrl: YOGA_IMG, amazonLink: "#" },
  ]},
  { slug: "surferos", title: "Los Mejores Regalos para Surferos", description: "Regalos para surferos.", products: [
    { id: "1", title: "Traje Neopreno", price: "129,99 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "2", title: "Leash Tabla", price: "24,00 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "3", title: "Cera Surf Pack", price: "12,90 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "4", title: "T shirt Surf", price: "28,99 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "5", title: "Towell Poncho", price: "35,00 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "6", title: "Gafas Sol Polarizadas", price: "45,50 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "7", title: "Taza Surfer", price: "11,99 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "8", title: "Reloj Resistente Agua", price: "89,99 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "9", title: "Bidón Aislante", price: "22,90 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "10", title: "Libro: Surf", price: "24,99 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "11", title: "Bolsas Secas", price: "18,00 €", imageUrl: SURFERO_IMG, amazonLink: "#" }, { id: "12", title: "Figura Surf", price: "34,50 €", imageUrl: SURFERO_IMG, amazonLink: "#" },
  ]},
  { slug: "buzos", title: "Los Mejores Regalos para Buzos", description: "Regalos para buceadores.", products: [
    { id: "1", title: "Máscara Buceo", price: "65,99 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "2", title: "Aletas Buceo", price: "89,00 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "3", title: "Snorkel Seco", price: "34,90 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "4", title: "Reloj Buceo", price: "199,99 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "5", title: "Linterna Submarina", price: "45,00 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "6", title: "Bolsas Secas", price: "18,50 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "7", title: "Towel Poncho", price: "28,99 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "8", title: "Taza Buzo", price: "11,99 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "9", title: "Libro: Buceo", price: "32,90 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "10", title: "Logbook Buceo", price: "22,99 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "11", title: "Figura Buzo", price: "24,00 €", imageUrl: BUZO_IMG, amazonLink: "#" }, { id: "12", title: "Camiseta Buceo", price: "28,50 €", imageUrl: BUZO_IMG, amazonLink: "#" },
  ]},
  { slug: "amantes-te", title: "Los Mejores Regalos para Amantes del Té", description: "Regalos para amantes del té.", products: [
    { id: "1", title: "Tetera Cerámica", price: "45,99 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "2", title: "Set Tazas Té", price: "35,00 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "3", title: "Infusor Bola", price: "12,90 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "4", title: "Té Verde Pack", price: "24,99 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "5", title: "Libro: Historia del Té", price: "28,00 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "6", title: "Reloj Arena Infusión", price: "18,50 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "7", title: "Organizador Tés", price: "22,99 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "8", title: "Taza Infusor Viaje", price: "24,99 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "9", title: "Pack Tés Mundo", price: "32,90 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "10", title: "Azucarero Porcelana", price: "18,99 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "11", title: "Galletas Té", price: "14,00 €", imageUrl: TE_IMG, amazonLink: "#" }, { id: "12", title: "Miel Premium", price: "22,50 €", imageUrl: TE_IMG, amazonLink: "#" },
  ]},
  { slug: "coleccionistas", title: "Los Mejores Regalos para Coleccionistas", description: "Regalos para coleccionistas.", products: [
    { id: "1", title: "Vitrina Display", price: "65,99 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "2", title: "Lupa Inspección", price: "28,00 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "3", title: "Álbum Coleccionables", price: "24,90 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "4", title: "Guantes Algodón", price: "12,99 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "5", title: "Estuche Protección", price: "18,00 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "6", title: "Libro: Coleccionismo", price: "32,50 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "7", title: "Lámpara Luz LED", price: "42,99 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "8", title: "Báscula Precisión", price: "28,99 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "9", title: "Organizador Cajas", price: "24,90 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "10", title: "Cuaderno Inventario", price: "16,99 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "11", title: "Lupa Digital", price: "55,00 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" }, { id: "12", title: "Taza Coleccionista", price: "11,99 €", imageUrl: COLECCIONISTA_IMG, amazonLink: "#" },
  ]},
  { slug: "astronomos", title: "Los Mejores Regalos para Astrónomos", description: "Regalos para astrónomos.", products: [
    { id: "1", title: "Telescopio Principiante", price: "149,99 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "2", title: "Libro: Atlas Estelar", price: "35,00 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "3", title: "Planisferio Celeste", price: "18,90 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "4", title: "Binoculares Astronómicos", price: "89,99 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "5", title: "Linterna Luz Roja", price: "22,00 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "6", title: "Cuaderno Observaciones", price: "14,50 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "7", title: "Taza Galaxia", price: "12,99 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "8", title: "Póster Sistema Solar", price: "24,99 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "9", title: "App Estrellas Premium", price: "9,90 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "10", title: "Silla Plegable Observación", price: "45,99 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "11", title: "Filtro Luna", price: "28,00 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" }, { id: "12", title: "Figura Planeta", price: "34,50 €", imageUrl: ASTRONOMO_IMG, amazonLink: "#" },
  ]},
  { slug: "historiadores", title: "Los Mejores Regalos para Historiadores", description: "Regalos para historiadores.", products: [
    { id: "1", title: "Libro: Historia Universal", price: "42,99 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "2", title: "Cuaderno Cuero", price: "28,00 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "3", title: "Pluma Estilográfica", price: "45,90 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "4", title: "Lupa Lectura", price: "18,99 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "5", title: "Mapa Histórico", price: "24,00 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "6", title: "Taza Historiador", price: "11,99 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "7", title: "Estuche Documentos", price: "35,50 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "8", title: "Lampara Escritorio", price: "42,99 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "9", title: "Agenda Académica", price: "22,90 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "10", title: "Diccionario Histórico", price: "38,99 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "11", title: "Organizador Fichas", price: "18,00 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" }, { id: "12", title: "Reproducción Antigua", price: "45,00 €", imageUrl: HISTORIADOR_IMG, amazonLink: "#" },
  ]},
  { slug: "arqueologos", title: "Los Mejores Regalos para Arqueólogos", description: "Regalos para arqueólogos.", products: [
    { id: "1", title: "Brocha Arqueológica", price: "18,99 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "2", title: "Pala Excavación", price: "28,00 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "3", title: "Cúter Precisión", price: "12,90 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "4", title: "Bolsas Muestras", price: "14,99 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "5", title: "Libro: Arqueología", price: "38,00 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "6", title: "Cuaderno Campo", price: "18,50 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "7", title: "Lupa Campo", price: "24,99 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "8", title: "Taza Arqueólogo", price: "11,99 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "9", title: "GPS Portátil", price: "89,90 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "10", title: "Cámara Compacta", price: "149,99 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "11", title: "Sombrero Campo", price: "22,00 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" }, { id: "12", title: "Botella Agua", price: "18,50 €", imageUrl: ARQUEOLOGO_IMG, amazonLink: "#" },
  ]},
  { slug: "actores", title: "Los Mejores Regalos para Actores", description: "Regalos para actores.", products: [
    { id: "1", title: "Libro: Interpretación", price: "28,99 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "2", title: "Espejo Maquillaje", price: "35,00 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "3", title: "Cuaderno Actor", price: "18,90 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "4", title: "Botella Voz", price: "12,99 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "5", title: "Taza Break a Leg", price: "11,99 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "6", title: "Reloj Elegante", price: "65,50 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "7", title: "Funda Script", price: "24,99 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "8", title: "Auriculares", price: "45,99 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "9", title: "Te Reparador", price: "14,90 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "10", title: "Libreta Bolsillo", price: "16,99 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "11", title: "Mascarilla Hidratante", price: "22,00 €", imageUrl: ACTOR_IMG, amazonLink: "#" }, { id: "12", title: "Figura Teatro", price: "34,50 €", imageUrl: ACTOR_IMG, amazonLink: "#" },
  ]},
  { slug: "bailarines", title: "Los Mejores Regalos para Bailarines", description: "Regalos para bailarines.", products: [
    { id: "1", title: "Zapatillas Danza", price: "45,99 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "2", title: "Rodillo Foam", price: "28,00 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "3", title: "Banda Elástica", price: "12,90 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "4", title: "Bolsa Danza", price: "35,99 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "5", title: "Crema Calentadora", price: "14,00 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "6", title: "Taza Bailarín", price: "11,99 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "7", title: "Espejo Pared", price: "65,50 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "8", title: "Colchoneta Ejercicio", price: "32,99 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "9", title: "Libro: Técnica", price: "24,90 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "10", title: "Botella Agua", price: "16,99 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "11", title: "Reloj Cronómetro", price: "22,00 €", imageUrl: BAILARIN_IMG, amazonLink: "#" }, { id: "12", title: "Pack Vitaminas", price: "28,50 €", imageUrl: BAILARIN_IMG, amazonLink: "#" },
  ]},
  { slug: "artistas", title: "Los Mejores Regalos para Artistas", description: "Regalos para artistas plásticos.", products: [
    { id: "1", title: "Set Pinceles", price: "38,99 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "2", title: "Paleta Madera", price: "18,00 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "3", title: "Lienzos Pack", price: "28,90 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "4", title: "Cuaderno Sketch", price: "22,99 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "5", title: "Caballete", price: "65,00 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "6", title: "Libro: Técnicas", price: "32,50 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "7", title: "Taza Artista", price: "11,99 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "8", title: "Bata Pintor", price: "24,99 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "9", title: "Acuarelas", price: "42,90 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "10", title: "Lápices Grafito", price: "18,99 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "11", title: "Easel Pared", price: "54,00 €", imageUrl: ARTISTA_IMG, amazonLink: "#" }, { id: "12", title: "Óleos Set", price: "48,50 €", imageUrl: ARTISTA_IMG, amazonLink: "#" },
  ]},
];

export function getNicheBySlug(slug: string): Niche | undefined {
  return NICHE_DATA.find((n) => n.slug === slug);
}

export function getAllSlugs(): string[] {
  return NICHE_DATA.map((n) => n.slug);
}
